version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.1
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      # - DB_VENDOR=mysql
      # - DB_ADDR=
      # - DB_PORT=
      # - DB_DATABASE=
      # - DB_USER=
      # - DB_PASSWORD=

    command: start-dev
    ports:
      - 9090:8080
      - 9443:8443