server:
  port: 8443
  ssl:
    enabled: true
    Key-store: classpath:certs/brasatech-server.p12
    key-store-password: changeit
    key-store-type: PKCS12
    Key-alias: brasatech-server

 


spring:
  application:
    name: gateway
  cloud:
    gateway:
      metrics:
        enabled: true
  security:
    oauth2:
      client:
        registration:
#          github:
#            client-id: 9484e4127e3482238e9d
#            client-secret: 205e8e88f06bcb884e0df777885f564c91cfbf2a
#            redirect-uri: "{baseUrl}/login/oauth2/code/github"
          gateway:
            provider: keycloak
            client-id: Gateway
            client-secret: iUlFnPr1YDFOwK1tAfsd9B61i2X7xqeb
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: https://brasatech.es:9443/realms/BrasaTech

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway        

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://brasatech.es:8761/eureka}
    healthcheck:
      enabled: true