server:
  port: 7443
  ssl:
    enabled: true
    Key-store: classpath:certs/brasatech-server.p12
    key-store-password: changeit
    key-store-type: PKCS12
    Key-alias: brasatech-server
    trust-store: classpath:certs/truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12




spring:
  application:
    name: gateway
  cloud:
    gateway:
      metrics:
        enabled: true
  security:
    oauth2:
      client:
        registration:
#          github:
#            client-id: 9484e4127e3482238e9d
#            client-secret: 205e8e88f06bcb884e0df777885f564c91cfbf2a
#            redirect-uri: "{baseUrl}/login/oauth2/code/github"
          gateway:
            provider: keycloak
            client-id: gateway
            client-secret: H5l9Upgtp1GWVD4nwD0WVrku4JIQglmF
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: https://localhost:9443/realms/eutm-filing

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway        

# eureka:
#   client:
#     registerWithEureka: true
#     serviceUrl:
#       defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
#     healthcheck:
#       enabled: true
